regions:
  africa:
    drc:
      name: Democratic Republic of the Congo
      flag: ğŸ‡¨ğŸ‡©
      osmcha.id: 40230cd7-2d13-4df7-bc1e-4ac44bb8478a
    ghana:
      name: Ghana
      flag: ğŸ‡¬ğŸ‡­
      osmcha.id: 0d8dfe15-dcd1-4f53-9c65-30bc164f61ef
    liberia:
      name: Liberia
      flag: ğŸ‡±ğŸ‡·
      osmcha.id: 20cc427e-7f55-4527-b355-88f0f4d67fea
    libya:
      name: Libya
      flag: ğŸ‡±ğŸ‡¾
      osmcha.id: b1e4eed6-dccb-4207-aecc-d9e5d6ca4871
    niger:
      name: Niger
      flag: ğŸ‡³ğŸ‡ª
      osmcha.id: 7c6d3558-823d-435b-adb0-ff0d06222419
    nigeria:
      name: Nigeria
      flag: ğŸ‡³ğŸ‡¬
      osmcha.id: c9a55728-9619-422b-abb0-e0fd55e0a780
    tanzania:
      name: Tanzania
      flag: ğŸ‡¹ğŸ‡¿
      osmcha.id: 4df237d7-07bb-4b43-afa0-357eb485e8e1
    togo:
      name: Togo
      flag: ğŸ‡¹ğŸ‡¬
      osmcha.id: 72be6502-f732-4a77-9311-0c2f49de6679
    uganda:
      name: Uganda
      flag: ğŸ‡ºğŸ‡¬
      osmcha.id: c17132f4-95eb-4b92-b93a-48c1a75cf3c3
  asia:
    bangladesh:
      name: Bangladesh
      flag: ğŸ‡§ğŸ‡©
      osmcha.id: 02900696-ec73-4ead-9784-115fc47dd6d0
    cambodia:
      name: Cambodia
      flag: ğŸ‡°ğŸ‡­
      osmcha.id: a4c7297c-ee0f-4196-84a2-348fcfc650d4
    china:
      name: China
      flag: ğŸ‡¨ğŸ‡³
      osmcha.id: 26f398a6-ab46-41cb-9a30-14b04031129a
    china-beijing:
      name: Beijing
      flag: ğŸ‡¨ğŸ‡³
      osmcha.id: 7f04c1ed-35f4-4fbf-bc36-9356e39ec438
    china-heilongjiang:
      name: Heilongjiang
      flag: ğŸ‡¨ğŸ‡³
      osmcha.id: e54192ee-b3bd-40c8-acda-11ca6e04a706
    china-hunan:
      name: Hunan
      flag: ğŸ‡¨ğŸ‡³
      osmcha.id: d58be17d-5181-4640-861d-eafaac565631
    east-timor:
      name: East Timor
      flag: ğŸ‡¹ğŸ‡±
      osmcha.id: 06163dc0-900f-4a6d-9127-21905edf299c
    hongkong:
      name: Hong Kong
      flag: ğŸ‡­ğŸ‡°
      osmcha.id: ddd87c1a-717b-4d30-815a-507ed8d57a3c
    india:
      name: India
      flag: ğŸ‡®ğŸ‡³
      osmcha.id: 27c935d1-c28f-4f0d-9b83-7487210a9027
    indonesia:
      name: Indonesia
      flag: ğŸ‡®ğŸ‡©
      osmcha.id: af24c9ea-4ba1-439f-80fd-0f7b30fa6952
    japan:
      name: Japan
      flag: ğŸ‡¯ğŸ‡µ
      osmcha.id: dca30c0e-cd95-4ca7-9c82-d0d7ec71c452
    laos:
      name: Laos
      flag: ğŸ‡±ğŸ‡¦
      osmcha.id: 8164870e-c677-4d1c-9229-9a56d75b6fdf
    macao:
      name: Macao
      flag: ğŸ‡²ğŸ‡´
      osmcha.id: 05c456ea-f4b3-4210-a091-55d9b8ec4705
    myanmar:
      name: Myanmar
      flag: ğŸ‡²ğŸ‡²
      osmcha.id: 4ecd8633-cfa9-4d0d-933a-50d8bcf5c97a
    north-korea:
      name: North Korea
      flag: ğŸ‡°ğŸ‡µ
      osmcha.id: c09f9eb0-4a5b-4f5d-b485-9ea9024b9b5e
    pakistan:
      name: Pakistan
      flag: ğŸ‡µğŸ‡°
      osmcha.id: cbf7911d-471c-4066-88d0-f35b6830aad3
    papua-new-guinea:
      name: Papua New Guinea
      flag: ğŸ‡µğŸ‡¬
      osmcha.id: 901b8eea-7a95-4937-88bc-e41930085dc2
    philippines:
      name: Philippines
      flag: ğŸ‡µğŸ‡­
      osmcha.id: 6f6dcbc8-8811-4e5c-934d-ebb13af0590a
    south-korea:
      name: South Korea
      flag: ğŸ‡°ğŸ‡·
      osmcha.id: de3cd652-a238-410c-8ad6-348ee35f64ca
    taiwan:
      name: Taiwan
      flag: ğŸ‡¹ğŸ‡¼
      osmcha.id: 71a6e5a5-8a9e-4c27-9e1d-f7e2031bafc9
    turkey:
      name: Turkey
      flag: ğŸ‡¹ğŸ‡·
      osmcha.id: e77ac469-aef9-4780-bc4b-57a445dceca3
    vietnam:
      name: Vietnam
      flag: ğŸ‡»ğŸ‡³
      osmcha.id: fb840b79-4bb6-472c-87e9-ef7e34378db6
  australia: []
  europe:
    albania:
      name: Albania
      flag: ğŸ‡¦ğŸ‡±
      osmcha.id: c11ff84e-ce82-465d-9885-aacbb1134422
    austria:
      name: Austria
      flag: ğŸ‡¦ğŸ‡¹
      osmcha.id: e1f0d692-edc1-4dc5-a84a-b7add29c6b90
    belgium:
      name: Belgium
      flag: ğŸ‡§ğŸ‡ª
      osmcha.id: 640be7af-1f93-4d9c-a521-66cfdd59e6b8
    bulgaria:
      name: Bulgaria
      flag: ğŸ‡§ğŸ‡¬
      osmcha.id: 1a15a041-57fa-4f5e-9813-ef8d4afe700d
    catalan_countries:
      name: Catalan Countries
      flag: ğŸ´ó ¥ó ³ó £ó ´ó ¿
      osmcha.id: 401dba26-ce0e-4f9f-8425-7b16506b4410
    dachli-obersee-rheintal:
      name: DACHLI-Obersee-Rheintal
      flag: 4ï¸
      osmcha.id: abfd17fc-2809-4285-86ab-1e0336a68915
    france:
      name: France
      flag: ğŸ‡«ğŸ‡·
      osmcha.id: 757de22c-1627-48f6-9fa9-86134e0c396b
    germany:
      name: Germany
      flag: ğŸ‡©ğŸ‡ª
      osmcha.id: dcef1d6f-db2f-4ff1-8b8b-48e1a6d85abb
    germany-berlin:
      name: Berlin
      flag: ğŸ‡©ğŸ‡ª
      osmcha.id: a5516ac3-4728-47bc-aac7-b444155ded7a
    germany-berlin-neukoelln:
      name: Berlin-NeukÃ¶lln
      flag: ğŸ‡©ğŸ‡ª
      osmcha.id: 56415477-5107-4647-934a-26b975f7da49
    germany-bremen:
      name: Bremen
      flag: ğŸ‡©ğŸ‡ª
      osmcha.id: 348c2d07-4503-4fec-a727-674259670ec5
    hungary:
      name: Hungary
      flag: ğŸ‡­ğŸ‡º
      osmcha.id: b874522b-99f2-4ef7-ad1f-b5d27323ca3a
    ireland:
      name: Ireland
      flag: â˜˜ï¸
      osmcha.id: dfa457d9-b30c-4034-baae-04a268408b39
    italy:
      name: Italy
      flag: ğŸ‡®ğŸ‡¹
      osmcha.id: ac2598cc-9b66-432e-b195-9b93e21c5d26
    kosovo:
      name: Kosovo
      flag: ğŸ‡½ğŸ‡°
      osmcha.id: 615b1303-2ff7-45d4-9eb2-659f60e06c9f
    luxembourg:
      name: Luxembourg
      flag: ğŸ‡±ğŸ‡º
      osmcha.id: 9188383c-271b-4d3e-9c2d-d212fb784937
    poland:
      name: Poland
      flag: ğŸ‡µğŸ‡±
      osmcha.id: 98d2b447-34b6-4681-82f8-9de3adddbf1b
    portugal:
      name: Portugal
      flag: ğŸ‡µğŸ‡¹
      osmcha.id: 0d965bcc-d718-4f92-b13e-92ccc217a825
    romania:
      name: Romania
      flag: ğŸ‡·ğŸ‡´
      osmcha.id: 34c3f6b6-8728-471e-8cee-d1545abbae91
    scotland:
      name: Scotland
      flag: ğŸ´ó §ó ¢ó ³ó £ó ´ó ¿
      osmcha.id: 2c2d94e5-29bc-4eaa-a5e2-119df5d6b649
    spain:
      name: Spain
      flag: ğŸ‡ªğŸ‡¸
      osmcha.id: e3402391-1831-4e71-a4f8-17f6a335a66b
    ukraine:
      name: Ukraine
      flag: ğŸ‡ºğŸ‡¦
      osmcha.id: 2453d07e-4c46-44eb-9b60-9b836338288d
  north-america:
    ca-bc:
      name: British Columbia
      flag: ğŸ‡¨ğŸ‡¦
      osmcha.id: 9e58ce7f-ad64-4d5f-9242-895c9ed428e0
    ca-on:
      name: Ontario
      flag: ğŸ‡¨ğŸ‡¦
      osmcha.id: e996293a-99b8-4fef-8321-f997c2ba7740
    panama:
      name: Panama
      flag: ğŸ‡µğŸ‡¦
      osmcha.id: 0a2b4874-4c19-45e3-8e75-8b40a8f7f3aa
    california:
      name: California
      flag: ğŸ‡ºğŸ‡¸
      osmcha.id: 766165a5-0a47-4cb8-8cde-d12fed551ff0
    kansas:
      name: Kansas
      flag: ğŸ‡ºğŸ‡¸
      osmcha.id: 68d8c9b6-ab1a-4837-89d4-1a558e398232
    massachusetts:
      name: Commonwealth of Massachusetts
      flag: ğŸ‡ºğŸ‡¸
      osmcha.id: 4cd5aef1-8bc3-4013-967b-dae167a9ee2a
    michigan:
      name: Michigan
      flag: ğŸ‡ºğŸ‡¸
      osmcha.id: a5d45476-3601-441e-b4e7-77b7d958e3a8
    newyork:
      name: New York State
      flag: ğŸ‡ºğŸ‡¸
      osmcha.id: be301bd2-e35c-45fe-bcff-17892fce6e2e
    ohio:
      name: Ohio
      flag: ğŸ‡ºğŸ‡¸
      osmcha.id: d525374c-7f38-468b-bb37-785bcdf85723
    oregon:
      name: Oregon
      flag: ğŸ‡ºğŸ‡¸
      osmcha.id: 2f110fd8-c4df-4917-b2cd-1ed098b1eafb
    utah:
      name: Utah
      flag: ğŸ‡ºğŸ‡¸
      osmcha.id: 236244c4-9835-4c3e-872c-f4125ea1632c
    vermont:
      name: Vermont
      flag: ğŸ‡ºğŸ‡¸
      osmcha.id: 41070e3d-787f-4cc0-b5e5-ab90eb227a96
    washington:
      name: Washington State
      flag: ğŸ‡ºğŸ‡¸
      osmcha.id: 968ad875-8065-4d55-ac9b-87b07bc6f1f5
  south-america:
    bolivia:
      name: Bolivia
      flag: ğŸ‡§ğŸ‡´
      osmcha.id: 2717cb5b-09c3-44e3-a7aa-8872b9506f0e
    chile:
      name: Chile
      flag: ğŸ‡¨ğŸ‡±
      osmcha.id: dc4766e3-6b07-454c-a777-56652b1dc438
    colombia:
      name: Colombia
      flag: ğŸ‡¨ğŸ‡´
      osmcha.id: ec24e3f4-ad8e-4ee9-9ad4-f7676c0b334a
    bogota:
      name: BogotÃ¡
      flag: ğŸ‡¨ğŸ‡´
      osmcha.id: 1aa040cb-4a72-44bf-af14-7cada5146534
