regions:
  belgium:
    name: Belgium
    flag: ðŸ‡§ðŸ‡ª
    locales: fr|nl|de
    osmcha.id: 640be7af-1f93-4d9c-a521-66cfdd59e6b8
  italy:
    name: Italy
    flag: ðŸ‡®ðŸ‡¹
    locales: it
    osmcha.id: ac2598cc-9b66-432e-b195-9b93e21c5d26
  luxembourg:
    name: Luxembourg
    flag: ðŸ‡±ðŸ‡º
    locales: fr|en|de
    osmcha.id: 9188383c-271b-4d3e-9c2d-d212fb784937
  washington:
    name: Washington State
    flag: ðŸ‡ºðŸ‡¸
    locales: en
    osmcha.id: 968ad875-8065-4d55-ac9b-87b07bc6f1f5
