regions:
  bangladesh:
    name: Bangladesh
    flag: ğŸ‡§ğŸ‡©
    locales: en
    osmcha.id: 02900696-ec73-4ead-9784-115fc47dd6d0
  belgium:
    name: Belgium
    flag: ğŸ‡§ğŸ‡ª
    locales: fr|nl|de
    osmcha.id: 640be7af-1f93-4d9c-a521-66cfdd59e6b8
  bulgaria:
    name: Bulgaria
    flag: ğŸ‡§ğŸ‡¬
    locales: bg
    osmcha.id: 1a15a041-57fa-4f5e-9813-ef8d4afe700d
  ca-bc:
    name: British Columbia
    flag: ğŸ‡¨ğŸ‡¦
    locales: en|fr
    osmcha.id: 9e58ce7f-ad64-4d5f-9242-895c9ed428e0
  colombia:
    name: Colombia
    flag: ğŸ‡¨ğŸ‡´
    locales: es
    osmcha.id: ec24e3f4-ad8e-4ee9-9ad4-f7676c0b334a
  bogota:
    name: BogotÃ¡
    flag: ğŸ‡¨ğŸ‡´
    locales: es
    osmcha.id: 1aa040cb-4a72-44bf-af14-7cada5146534
  drc:
    name: Democratic Republic of the Congo
    flag: ğŸ‡¨ğŸ‡©
    locales: fr
    osmcha.id: 40230cd7-2d13-4df7-bc1e-4ac44bb8478a
  ghana:
    name: Ghana
    flag: ğŸ‡¬ğŸ‡­
    locales: en
    osmcha.id: 0d8dfe15-dcd1-4f53-9c65-30bc164f61ef
  italy:
    name: Italy
    flag: ğŸ‡®ğŸ‡¹
    locales: it
    osmcha.id: ac2598cc-9b66-432e-b195-9b93e21c5d26
  japan:
    name: Japan
    flag: ğŸ‡¯ğŸ‡µ
    locales: ja
    osmcha.id: dca30c0e-cd95-4ca7-9c82-d0d7ec71c452
  libya:
    name: Libya
    flag: ğŸ‡±ğŸ‡¾
    locales: en
    osmcha.id: b1e4eed6-dccb-4207-aecc-d9e5d6ca4871
  luxembourg:
    name: Luxembourg
    flag: ğŸ‡±ğŸ‡º
    locales: fr|en|de
    osmcha.id: 9188383c-271b-4d3e-9c2d-d212fb784937
  panama:
    name: Panama
    flag: ğŸ‡µğŸ‡¦
    locales: es
    osmcha.id: 0a2b4874-4c19-45e3-8e75-8b40a8f7f3aa
  poland:
    name: Poland
    flag: ğŸ‡µğŸ‡±
    locales: pl
    osmcha.id: 98d2b447-34b6-4681-82f8-9de3adddbf1b
  romania:
    name: RomÃ¢nia
    flag: ğŸ‡·ğŸ‡´
    locales: ro
  tanzania:
    name: Tanzania
    flag: ğŸ‡¹ğŸ‡¿
    locales: en
    osmcha.id: 4df237d7-07bb-4b43-afa0-357eb485e8e1
  uganda:
    name: Uganda
    flag: ğŸ‡ºğŸ‡¬
    locales: en
    osmcha.id: c17132f4-95eb-4b92-b93a-48c1a75cf3c3
  kansas:
    name: Kansas
    flag: ğŸ‡ºğŸ‡¸
    locales: en
    osmcha.id: 68d8c9b6-ab1a-4837-89d4-1a558e398232
  massachusetts:
    name: Commonwealth of Massachusetts
    flag: ğŸ‡ºğŸ‡¸
    locales: en
    osmcha.id: 4cd5aef1-8bc3-4013-967b-dae167a9ee2a
  newyork:
    name: New York State
    flag: ğŸ‡ºğŸ‡¸
    locales: en
    osmcha.id: be301bd2-e35c-45fe-bcff-17892fce6e2e
  washington:
    name: Washington State
    flag: ğŸ‡ºğŸ‡¸
    locales: en
    osmcha.id: 968ad875-8065-4d55-ac9b-87b07bc6f1f5
