regions:
  belgium:
    name: Belgium
    flag: ğŸ‡§ğŸ‡ª
    locales: fr|nl|de
    osmcha.id: 640be7af-1f93-4d9c-a521-66cfdd59e6b8
  ghana:
    name: Ghana
    flag: ğŸ‡¬ğŸ‡­
    locales: en
    osmcha.id:
  italy:
    name: Italy
    flag: ğŸ‡®ğŸ‡¹
    locales: it
    osmcha.id: ac2598cc-9b66-432e-b195-9b93e21c5d26
  luxembourg:
    name: Luxembourg
    flag: ğŸ‡±ğŸ‡º
    locales: fr|en|de
    osmcha.id: 9188383c-271b-4d3e-9c2d-d212fb784937
  massachusetts:
    name: Commonwealth of Massachusetts
    flag: ğŸ‡ºğŸ‡¸
    locales: en
    osmcha.id: 4cd5aef1-8bc3-4013-967b-dae167a9ee2a
  newyork:
    name: New York State
    flag: ğŸ‡ºğŸ‡¸
    locales: en
    osmcha.id: be301bd2-e35c-45fe-bcff-17892fce6e2e
  uganda:
    name: Uganda
    flag: ğŸ‡ºğŸ‡¬
    locales: en
    osmcha.id: c17132f4-95eb-4b92-b93a-48c1a75cf3c3
  washington:
    name: Washington State
    flag: ğŸ‡ºğŸ‡¸
    locales: en
    osmcha.id: 968ad875-8065-4d55-ac9b-87b07bc6f1f5
